### ISSUE TITLE
Use unicode for degree sign in CompassGauge demo sample

### ISSUE THREAD

**Issue by ltorok** [HanSolo/medusademo#1]
It would be better to use for degree sign in CompassGauge demo sample unicode \u00B0 character.
I have on my Windows 10 all settings for Region in Slovak - Formats, Location, a degree sign is displayed wrong. When replace with unicode, then is OK. Thanks.

**Comment by ltorok** [comment]
I see, that already fixed, but in constructor value = new Label() for init disalying just is not...

**Comment by ltorok** [comment]
Please use unicode for degree sign in InteractiveDemo and Overviewdemo (gauge5 and gauge17 for unit()). Thanks.

**Comment by HanSolo** [comment]
Argh...sorrrrrry...fixed :)

**Comment by ltorok** [comment]
And InteractiveDemo? In OverviewDemo is for clock2 title set to "Münster", please unicode for "ü". Very good job. Thanks.
