### ISSUE TITLE
Built file will not run

### ISSUE THREAD

**Issue by digitig** [HanSolo/medusademo#4]
I've built the file with
_gradlew clean_
_gradlew build_

When I invoke _java -jar build\classes\main\eu\hansolo\ActivityDashboard.class_ I get an error:
_Error: Invalid or corrupt jarfile build\classes\main\eu\hansolo\ActivityDashboard.class_

I note that ActivityDashboard.java has a dependency on eu.hansolo.colors.MaterialDesign, which is neither in the Medusa distribution nor the MedusaDemo distribution. That might be related and is preventing me doing my own build configuration.

**Comment by HanSolo** [comment]
Could you try again with the latest commit?

**Comment by HanSolo** [comment]
To avoid those problems I've added tasks for every demo to the gradle file. So now you can start the ActivityDashboard simply by calling "gradle ActivityDashboard"
